// Regenerate with `cd src-tauri && UPDATE_BINDINGS=1 cargo test`.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	ping: (request: PingRequest) => typedError<PingReply, PingError>(__TAURI_INVOKE("ping", { request })),
};

/* Types */
export type PingError = { kind: "empty" } | { kind: "tooLong"; data: {
	max: number,
} };

export type PingReply = {
	echo: string,
	version: string,
};

export type PingRequest = {
	message: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

